# Use root/example as user/password credentials
version: '3.1'

services:
  mysql-8-0-36:
    image: mysql:8.0.36
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql.8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.0-standalone
    container_name: adminer
    restart: always
    ports:
      - 8082:8080
